consumes:
- application/json
definitions:
  model.Album:
    properties:
      artist:
        description: 這裡的註解會進到 swagger
        type: string
      id:
        description: 唯一編號
        type: string
      price:
        type: number
      title:
        description: 標題
        type: string
    required:
    - artist
    - price
    - title
    type: object
  utils.Config:
    properties:
      dsn:
        type: string
      host:
        type: string
    required:
    - host
    type: object
info:
  contact:
    email: a0970785699@gmail.com
    name: system designer
    url: https://github.com/leon123858/committee-meeting-assistan
  description: This is the API server about data access for CMA system
  title: CMA data api
  version: 0.0.1
paths:
  /albums:
    get:
      description: get list of albums
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Album'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/model.Album'
            type: array
      security:
      - Bearer: []
      summary: albums example
      tags:
      - album
    post:
      description: post list of albums
      parameters:
      - description: album 實體結構, id 不用
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Album'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Config'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Config'
      security:
      - Bearer: []
      summary: postAlbums adds an album from JSON received in the request body.
      tags:
      - album
  /albums/{id}:
    get:
      description: parameter sent by the client, then returns that album as a response.
      parameters:
      - description: 要抓的目標的 id ,唯一編號
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Album'
      security:
      - Bearer: []
      summary: getAlbumByID locates the album whose ID value matches the id
      tags:
      - album
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: Type your api key
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
